#[macro_export]
macro_rules! fn_typed {
    ($obj:ident.$func:ident, $datatype:expr$(, $arg:expr)* => $then:expr) => {
        match $datatype {
            crate::Datatype::Int8 => $then($obj.$func::<i8>()),
            crate::Datatype::Int16 => $then($obj.$func::<i16>()),
            crate::Datatype::Int32 => $then($obj.$func::<i32>()),
            crate::Datatype::Int64 => $then($obj.$func::<i64>()),
            crate::Datatype::UInt8 => $then($obj.$func::<u8>()),
            crate::Datatype::UInt16 => $then($obj.$func::<u16>()),
            crate::Datatype::UInt32 => $then($obj.$func::<u32>()),
            crate::Datatype::UInt64 => $then($obj.$func::<u64>()),
            crate::Datatype::Float32 => $then($obj.$func::<f32>()),
            crate::Datatype::Float64 => $then($obj.$func::<f64>()),
            crate::Datatype::Char => unimplemented!(),
            crate::Datatype::StringAscii => unimplemented!(),
            crate::Datatype::StringUtf8 => unimplemented!(),
            crate::Datatype::StringUtf16 => unimplemented!(),
            crate::Datatype::StringUtf32 => unimplemented!(),
            crate::Datatype::StringUcs2 => unimplemented!(),
            crate::Datatype::StringUcs4 => unimplemented!(),
            crate::Datatype::Any => unimplemented!(),
            crate::Datatype::DateTimeYear => unimplemented!(),
            crate::Datatype::DateTimeMonth => unimplemented!(),
            crate::Datatype::DateTimeWeek => unimplemented!(),
            crate::Datatype::DateTimeDay => unimplemented!(),
            crate::Datatype::DateTimeHour => unimplemented!(),
            crate::Datatype::DateTimeMinute => unimplemented!(),
            crate::Datatype::DateTimeSecond => unimplemented!(),
            crate::Datatype::DateTimeMillisecond => unimplemented!(),
            crate::Datatype::DateTimeMicrosecond => unimplemented!(),
            crate::Datatype::DateTimeNanosecond => unimplemented!(),
            crate::Datatype::DateTimePicosecond => unimplemented!(),
            crate::Datatype::DateTimeFemtosecond => unimplemented!(),
            crate::Datatype::DateTimeAttosecond => unimplemented!(),
            crate::Datatype::TimeHour => unimplemented!(),
            crate::Datatype::TimeMinute => unimplemented!(),
            crate::Datatype::TimeSecond => unimplemented!(),
            crate::Datatype::TimeMillisecond => unimplemented!(),
            crate::Datatype::TimeMicrosecond => unimplemented!(),
            crate::Datatype::TimeNanosecond => unimplemented!(),
            crate::Datatype::TimePicosecond => unimplemented!(),
            crate::Datatype::TimeFemtosecond => unimplemented!(),
            crate::Datatype::TimeAttosecond => unimplemented!(),
            crate::Datatype::Blob => unimplemented!(),
            crate::Datatype::Boolean => unimplemented!(),
            crate::Datatype::GeometryWkb => unimplemented!(),
            crate::Datatype::GeometryWkt => unimplemented!(),
        }
    };
}
