
name: Install TileDB

inputs:
  token:
    description: 'A Github PAT'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Tarball Name
      shell: bash
      run: |
        OS=$(uname -o | tr '[:upper:]' '[:lower:]' | tr '/' '-')
        ARCH=$(uname -m)
        echo "TDB_TARBALL_NAME=libtiledb-$OS-$ARCH.tar.gz" >> $GITHUB_ENV
    - uses: robinraju/release-downloader@v1
      with:
        repository: 'TileDB-Inc/tiledb-rs'
        tag: nightly-libtiledb
        fileName: ${{ env.TDB_TARBALL_NAME }}
        extract: false
        token: ${{ inputs.token }}
    - name: Install TileDB
      shell: bash
      run: |
        mkdir -p /opt/github-actions
        tar -C /opt/github-actions -xzf ${{ env.TDB_TARBALL_NAME }}
        echo "PKG_CONFIG_PATH=/opt/github-actions/lib/pkgconfig" >> $GITHUB_ENV
