
name: Install TileDB

inputs:
  version:
   required: false
   description: "The version of TileDB to Install"
   default: "2.21.0/tiledb-linux-x86_64-2.21.0-0ea9c13"

runs:
  using: "composite"
  steps:
    - name: Install Conda
      uses: conda-incubator/setup-miniconda@v3
    - name: Install TileDB
      shell: bash
      run: |
        set -e pipefail
        # Add conda-forge for aws-crt-cpp
        conda config --add channels conda-forge
        # Install TileDB Nightly
        conda install tiledb/label/nightlies::tiledb
        # Setup pkg-config paths
        echo "PKG_CONFIG_PATH=$CONDA/lib/pkgconfig" >> $GITHUB_ENV
