# Keep in sync with the TileDB-Inc/TileDB Release workflow
- platform: windows-x86_64
  os: windows-2022
  triplet: x64-windows-release
- platform: linux-x86_64
  os: ubuntu-20.04
  manylinux: quay.io/pypa/manylinux_2_28_x86_64
  triplet: x64-linux-release
- platform: linux-x86_64-noavx2
  os: ubuntu-20.04
  cmake_args: -DCOMPILER_SUPPORTS_AVX2=OFF
  triplet: x64-linux-release
  manylinux: quay.io/pypa/manylinux_2_28_x86_64
- platform: linux-aarch64
  os: linux-arm64-ubuntu24
  triplet: arm64-linux-release
  manylinux: quay.io/pypa/manylinux_2_28_aarch64
- platform: macos-x86_64
  os: macos-13
  cmake_args: -DCMAKE_OSX_ARCHITECTURES=x86_64
  MACOSX_DEPLOYMENT_TARGET: 11
  triplet: x64-osx-release
- platform: macos-arm64
  os: macos-latest
  cmake_args: -DCMAKE_OSX_ARCHITECTURES=arm64
  MACOSX_DEPLOYMENT_TARGET: 11
  triplet: arm64-osx-release
