on:
  workflow_call:
  workflow_dispatch:

  push:
    branches:
      - main
      - refs/tags/*
  pull_request:
    branches:
      - '*'  # must quote since "*" is a YAML reserved character; we want a string

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: Clippy check

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
