on:
  schedule:
    # runs every day at 1:45 UTC
    - cron: "45 01 * * *"
  workflow_dispatch:
  pull_request:
    branches:
      - '*'  # must quote since "*" is a YAML reserved character; we want a string

name: Stable Build and Test Nightly

jobs:
  update_build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install TileDB
        run: |
          set -e pipefail
          echo "Starting"
          set -x
          echo "Make directory /opt/tiledb"
          mkdir -p /opt/tiledb
          echo "cd /opt/tiledb"
          cd /opt/tiledb
          echo "Getting release"
          https://github.com/TileDB-Inc/TileDB/releases/download/2.21.1/tiledb-linux-x86_64-2.21.1-acd5c50.tar.gz
          wget -q ${RELEASES_URL}/2.21.1/tiledb-linux-x86_64-2.21.1-acd5c50.tar.gz
          echo "Getting checksum"
          wget -q ${RELEASES_URL}/2.21.1/tiledb-linux-x86_64-2.21.1-acd5c50.tar.gz.sha256
          echo "Checking checksum"
          sha256sum tiledb*.sha256
          echo "Untarring"
          tar -C /opt/tiledb -xzf tiledb*.tar.gz
          echo "Done"
      - name: Install TileDB Log Dump
        if: ${{ failure() }}
        run: |
          cat ${TILEDB_INSTALL_LOG}
      - name: Check Formatting
        run: cargo fmt --quiet --check
      - name: Update Dependencies
        run: cargo update --recursive
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -Dwarnings
      - name: Build
        run: cargo build --all-targets --all-features
      - name: Test
        run: cargo test --all-targets --all-features

  create_issue_on_fail:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    needs: update_build_and_test
    if: failure() || cancelled()
    steps:
      - uses: actions/checkout@v3
      - name: Create Issue on Failure
        uses: TileDB-Inc/github-actions/open-issue@main
        with:
          name: Nightly Build Failure
          label: nightly-failure
          assignee: davisp,rroelke
