name: Static Nightlies
on:
  schedule:
    # runs every day at 1:45 UTC
    - cron: "45 01 * * *"
  workflow_dispatch:

jobs:
  test:
    name: Test Static Build
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout tiledb-rs
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Test
        run: cargo test --all-targets --all-features
        env:
          # Building against a static version of libtiledb
          TILEDB_SYS_STATIC: true
          # Limit parallel compilation jobs to avoid exhausting RAM
          TILEDB_SYS_JOBS: 4
      - name: Assert Static Linkage
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: .github/scripts/ubuntu-check-static-linkage.sh
      - name: Assert Static Linkage
        if: ${{ startsWith(matrix.os, 'macos-') }}
        run: .github/scripts/macos-check-static-linkage.sh

  create_issue_on_fail:
    name: Create Issue on Fail
    permissions:
      issues: write
    runs-on: ubuntu-latest
    needs: test
    if: failure() || cancelled()
    steps:
      - uses: actions/checkout@v3
      - name: Create Issue on Failure
        uses: TileDB-Inc/github-actions/open-issue@main
        with:
          name: Nightly Build Failure
          label: nightly-failure
          assignee: davisp,rroelke
