on:
  schedule:
    # runs every day at 1:45 UTC
    - cron: "45 01 * * *"
  workflow_dispatch:

name: Stable Build and Test Nightly

jobs:
  update_build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install TileDB
        run: |
          set -e pipefail
          mkdir -p /opt/tiledb
          cd /opt/tiledb
          wget -q ${RELEASES_URL}/2.21.0/tiledb-linux-x86_64-2.21.0-0ea9c13.tar.gz
          wget -q ${RELEASES_URL}/2.21.0/tiledb-linux-x86_64-2.21.0-0ea9c13.tar.gz.sha256
          sha256sum tiledb*.sha256
          tar -C /opt/tiledb -xzf tiledb*.tar.gz
      - name: Check Formatting
        run: cargo fmt --quiet --check
      - name: Update Dependencies
        run: cargo update --recursive
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -Dwarnings
      - name: Build
        run: cargo build --all-targets --all-features
      - name: Test
        run: cargo test --all-targets --all-features

  create_issue_on_fail:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    needs: update_build_and_test
    if: failure() || cancelled()
    steps:
      - uses: actions/checkout@v3
      - name: Create Issue on Failure
        uses: TileDB-Inc/github-actions/open-issue@main
        with:
          name: Nightly Build Failure
          label: nightly-failure
          assignee: davisp,rroelke
